### ISSUE TITLE
Weird jumping in queue when continuing audio book

### ISSUE THREAD

**Issue by SimonSimCity** [bcc-code/bmm-app#277]
When continuing an audiobook it seems that the queue does not play from top to bottom but jumps for some reason...

https://user-images.githubusercontent.com/392589/195025603-b6309b2e-41ba-4032-9e13-789654c711c0.mp4

**Comment by akrol95** [comment]
Hi @SimonSimCity 

Thank you for your report.

I was trying to reprodue this issue on many different ways, but it always works for me.
Can you please check again, you can easily reproduce this issue again on your phone?
If so, can you share more information with exact steps to reproduce and app version, android version and phone model?

**Comment by SimonSimCity** [comment]
Wasn't able to repeat it anymore these days, I'll reopen if I get it reproduced again...
