### ISSUE TITLE
[Discussion] Rethink shuffle option in the player

### ISSUE THREAD

**Issue by SimonSimCity** [bcc-code/bmm-app#304]
Rethink the function of shuffling: Yesterday I was listening to my favorite playlist. As I know the order of songs, I played it as shuffle. Today, I wanted to listen to an audio book, so I started the first track. It was quite a surprise to me that it continued with the 33rd chapter after having finished the first 😂 UX background: currently, when shuffling a playlist, the "shuffle" action is stored as part of the player. So when replacing the queue, this option is kept on the player, which I, as a user, would see as undesirable.

**Proposal 1** (quick fix): turn off the shuffle-option when replacing the queue.

**Proposal 2** (might be a better fit..): The shuffle option might not be a good place to have in the player in the first place. This also just overly complicates many other decisions as well. Shuffling should happen before adding the playlist or album to the (empty) queue. Once added, the player should just play down the queue, it should not have a memory of if the option of shuffling was used. This would be in contrast with how most players have it, in which you can shuffle or unshuffle a playlist.

Additions? Do you disagree?

**Comment by kkuepper** [comment]
today, we started changing it: #290 
Please comment on #290 if you have some feedback about the planned changes
