### ISSUE TITLE
allow for translation in UI

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-app#366]
- We should handle it gracefully if the text is too long. 
  - scale the font size so it fits
  - make the button wider

![photo_2023-01-24 11 02 13](https://user-images.githubusercontent.com/649978/214344338-2550cb80-48ff-4f55-bf5f-0b2efdb86bec.jpeg)

**Comment by akrol95** [comment]
@kkuepper What is this iPhone model?
