### ISSUE TITLE
[Android] Credits show placeholders instead of actual information

### ISSUE THREAD

**Issue by jaoord** [bcc-code/bmm-app#404]
So far I have only seen this on Android in app version 1.77.0. Works fine in iOS app v1.77

To reproduce:

1. Click More information on a track
2. Leave credits open
3. In the player select the next track
4. Click More information on that track

![photo1683969607](https://github.com/bcc-code/bmm-app/assets/6464609/f2aeb5ea-cb44-4eaa-9aab-53ab6c25f67f)

**Comment by akrol95** [comment]
@jaoord Thank you for the report. This issue will be fixed in the next release.
