### ISSUE TITLE
research custom app icon

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-app#436]

**Comment by akrol95** [comment]
For iOS it is doable: https://developer.apple.com/documentation/xcode/configuring_your_app_to_use_alternate_app_icons

On Android there is no direct feature for that, but i see some people do some magic hacks and apparently it's working: https://stackoverflow.com/questions/1103027/how-to-change-an-application-icon-programmatically-in-android

I think on Android it may behave differently on various custom launchers, but in the worst case the default icon will be displayed, so I think we can try.
