### ISSUE TITLE
biblestudy UI fixes

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-app#505]
Tasks for Arek (ordered by importance)

- [x] ask question textfield should get immediate focus on on-screen-keyboard show up (I think .BecomeFirstResponder() fixed it on iOS)
- [x] Android: green circle behind icon
- [x] dark mode: HasListened checkmark on podcastVM (iOS)
- [x] icon color in green circle should use global.black.1 (see 1st screenshot)
- [x] Point area should be centered in available space (see 2nd screenshot) (Søren suggests padding, but that could cause problems on smaller screens or longer translations)
- [ ] progress icon: flickers when expanding on iOS
- [x] progress icon: dynamic color

Tasks already done by Karsten

- [x] is "rules for points" translatable?
- [x] your progress icon
- [x] persist expanded state
- [x] does achievement detection still work?
- [x] some easy fixes for Dark mode
- [x] should we preload the webview at app start to make the webview load faster?

**Comment by kkuepper** [comment]
Design bugs found by Søren:

<img width="244" alt="Screenshot 2023-12-15 at 3 39 53 PM" src="https://github.com/bcc-code/bmm-app/assets/649978/88341ea3-2004-4a4b-b4b0-0bdba6014d99">

<img width="314" alt="Screenshot 2023-12-15 at 3 40 48 PM" src="https://github.com/bcc-code/bmm-app/assets/649978/a250c52f-69db-4b5f-8589-6ee3a57a9688">

**Comment by frederik-floor** [comment]
![IMG_7917](https://github.com/bcc-code/bmm-app/assets/86231761/23111213-26d0-422d-b254-a8a3a9ce0b8a)
Text under status number is wrong color.


https://github.com/bcc-code/bmm-app/assets/86231761/600f7a25-8c83-48a6-a60c-92b274d5851b

The achievement badges reload every time I refresh or start the app, and they take a long time to appear.

**Comment by frederik-floor** [comment]
Some comments about the question section:
![IMG_7919](https://github.com/bcc-code/bmm-app/assets/86231761/4b66b73d-699b-4d23-b4d4-c0700e518409)
![IMG_7920](https://github.com/bcc-code/bmm-app/assets/86231761/cc280092-0d77-4421-86bd-c8ed202ab858)

https://github.com/bcc-code/bmm-app/assets/86231761/3d7005ca-88b9-47c1-beab-eea92fd87b31
