### ISSUE TITLE
replace link to SongTreasures

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-app#557]
instead of sending users to SongTreasures, load the lyrics and show them in BMM.

Reason for this work item: SongTreasures pauses all playbacks when opening the app, thereby stopping the song that users try to read along.

- [x] app can show lyrics
- [x] set HasTranscription on track
- [x] return SearchableTranscription when loading transcription
- [x] add link to "Åpne SongTreasures" (norwegian only)
- [x] is it annoying to have a link on every song? (maybe only for Fra Kåre episodes, since there's no way to get lyrics otherwise)

from 'Tracks'
where Id == 106620 or startswith(Rel.Url, "https://sos.ham.no")

**Comment by mulundapm** [comment]
blocked by app updates

**Comment by mulundapm** [comment]
For summer conference 28.juli meeting, it shows the lyrics within the app but i dont see an "Åpne SongTreasures" option https://bmm.brunstad.org/admin/track/114725
