### ISSUE TITLE
BMM: hung up player on Android

### ISSUE THREAD

**Issue by kkuepper** [bcc-code/bmm-app#578]
Theory: The new bug where people get stuck, seems to only happen on Samsung with Android 14.

- https://projects.bcc.no/desk/tickets/10640803/messages
- https://projects.bcc.no/desk/tickets/10639075/messages
- Steven on Telegram
- https://projects.bcc.no/desk/tickets/10642871
- https://projects.bcc.no/desk/tickets/10645786
- https://projects.bcc.no/desk/tickets/10647703
- https://projects.bcc.no/desk/tickets/10648008
- https://projects.bcc.no/desk/tickets/10648623

**Comment by kkuepper** [comment]
"Empty player" happens more often when we have Fra Kåre.
![Screenshot 2024-10-02 at 3 02 23 PM](https://github.com/user-attachments/assets/54b12f53-8aed-4cf3-ac6d-a084a34129c5)

**Comment by sueczy** [comment]
https://github.com/user-attachments/assets/dbc1e334-91fd-47de-a626-b62a8429c855

Screen recording from one of the users @kkuepper

**Comment by kkuepper** [comment]
@mulundapm This should be fixed in 1.103.0-alpha41. Can you already test it? I'd like to roll it out tomorrow.

This bug probably still exists but at least BMM is no longer unusable: https://github.com/bcc-code/bccm-player/issues/72

**Comment by mulundapm** [comment]
We no longer have an android14 samsung in the office

**Comment by sueczy** [comment]
@kkuepper is it fixed now? Should I ask the users that reported that if they can confirm it's no longer happening for them?

**Comment by kkuepper** [comment]
@sueczy It's fixed in beta1, but beta1 introduces another (probably worse) bug: Personal playlists can't be loaded anymore, which also breaks the download function.

**Comment by kkuepper** [comment]
1.103.0-beta2 with the fix is now available on the Play Store.
